import { RateRule, CompanyProfile } from '../types';

export const BRAND_COLORS = {
  primary: '#2d3e50',      // Primary Dark Blue/Slate
  primaryDark: '#1e293b',  // Deep Slate hover
  orange: '#eb8a23',       // Primary Brand Orange
  orangeHover: '#d97917',  // Dark Orange hover
  accentYellow: '#e8a020', // Yellow-Orange accent
  bgLight: '#f8fafc',
  borderLight: '#e2e8f0',
};

export const DEFAULT_RATES: RateRule[] = [
  {id:1,  client:"Abhiyan Capital",                       state:"",           flat:null, s1k:50,   s1r:1500, s2k:null, s2r:1800, s3r:null, other:500  },
  {id:2,  client:"Aditya Birla Capital - PD",             state:"",           flat:null, s1k:30,   s1r:800,  s2k:null, s2r:1000, s3r:null, other:null },
  {id:3,  client:"Aditya Birla Housing Finance",          state:"",           flat:800,  s1k:null, s1r:null, s2k:null, s2r:null, s3r:null, other:null },
  {id:4,  client:"Auxilo Finserve Pvt. Ltd.",             state:"",           flat:null, s1k:15,   s1r:1000, s2k:25,   s2r:1800, s3r:2250, other:null },
  {id:5,  client:"Avanse Financial Pvt. Ltd",             state:"Delhi",      flat:null, s1k:25,   s1r:800,  s2k:40,   s2r:1000, s3r:1200, other:null },
  {id:6,  client:"Avanse Financial Pvt. Ltd",             state:"Other",      flat:null, s1k:25,   s1r:1000, s2k:40,   s2r:1200, s3r:1500, other:null },
  {id:7,  client:"Axis Bank Ltd. - PD",                  state:"",           flat:null, s1k:null, s1r:null, s2k:null, s2r:null, s3r:null, other:null },
  {id:8,  client:"Cent Bank",                             state:"",           flat:null, s1k:null, s1r:null, s2k:null, s2r:null, s3r:null, other:null },
  {id:9,  client:"Chola LIP",                             state:"",           flat:null, s1k:null, s1r:null, s2k:null, s2r:null, s3r:null, other:null },
  {id:10, client:"DCB Bank",                              state:"",           flat:null, s1k:25,   s1r:1500, s2k:null, s2r:2000, s3r:null, other:null },
  {id:11, client:"Godrej Capital Limited",                state:"",           flat:null, s1k:30,   s1r:900,  s2k:null, s2r:1200, s3r:null, other:null },
  {id:12, client:"ICICI Bank Ltd. - Delhi",               state:"",           flat:500,  s1k:null, s1r:null, s2k:null, s2r:null, s3r:null, other:null },
  {id:13, client:"ICICI PD_Ilens",                        state:"",           flat:null, s1k:15,   s1r:500,  s2k:null, s2r:700,  s3r:null, other:null },
  {id:14, client:"IDFC First Bank Ltd.",                  state:"",           flat:1000, s1k:null, s1r:null, s2k:null, s2r:null, s3r:null, other:null },
  {id:15, client:"India Bulls Finance / Samman Capital",  state:"",           flat:1000, s1k:null, s1r:null, s2k:null, s2r:null, s3r:null, other:null },
  {id:16, client:"India Shelter Finance Corp - PD",       state:"",           flat:1000, s1k:null, s1r:null, s2k:null, s2r:null, s3r:null, other:null },
  {id:17, client:"Jana Small Finance Bank",               state:"",           flat:null, s1k:30,   s1r:1000, s2k:50,   s2r:1300, s3r:null, other:null },
  {id:18, client:"Kotak Mahindra Bank Ltd. - PD",        state:"",           flat:null, s1k:25,   s1r:900,  s2k:null, s2r:1200, s3r:null, other:null },
  {id:19, client:"Moneyboxx Finance Ltd.",                state:"",           flat:1600, s1k:null, s1r:null, s2k:null, s2r:null, s3r:null, other:null },
  {id:20, client:"Piramal PD",                            state:"",           flat:null, s1k:40,   s1r:1000, s2k:null, s2r:1200, s3r:null, other:null },
  {id:21, client:"Piramal UP East - PD",                  state:"",           flat:null, s1k:40,   s1r:1000, s2k:null, s2r:1200, s3r:null, other:null },
  {id:22, client:"Shivalik Small Finance Bank - PD",      state:"",           flat:null, s1k:20,   s1r:1000, s2k:null, s2r:1300, s3r:null, other:null },
  {id:23, client:"Shivalik Small Finance Bank - LIP",     state:"",           flat:null, s1k:20,   s1r:1500, s2k:null, s2r:2200, s3r:null, other:null },
  {id:24, client:"SMFG India Credit Co. - PD",           state:"UP & UK",    flat:null, s1k:30,   s1r:850,  s2k:null, s2r:1200, s3r:null, other:null },
  {id:25, client:"SMFG India Credit Co. - PD",           state:"Haryana",    flat:900,  s1k:null, s1r:null, s2k:null, s2r:null, s3r:null, other:null },
  {id:26, client:"SMFG India Credit Co. - PD",           state:"Delhi NCR",  flat:750,  s1k:null, s1r:null, s2k:null, s2r:null, s3r:null, other:null },
  {id:27, client:"SMFG India Credit Co. - PD",           state:"Punjab/HP",  flat:null, s1k:20,   s1r:900,  s2k:null, s2r:1300, s3r:null, other:null },
  {id:28, client:"TATA Capital Finance - MBL/BIL",       state:"",           flat:800,  s1k:null, s1r:null, s2k:null, s2r:null, s3r:null, other:null },
  {id:29, client:"TATA Capital Limited - UCL",            state:"",           flat:800,  s1k:null, s1r:null, s2k:null, s2r:null, s3r:null, other:null },
];

export const DEFAULT_MAP: Record<string, string> = {
  "Abhiyan Capital":                                  "Abhiyan Capital",
  "Aditya Birla Capital-PD":                          "Aditya Birla Capital - PD",
  "Aditya Birla Housing Finance Limited-PD":          "Aditya Birla Housing Finance",
  "Auxilo Finserve Pvt Ltd":                          "Auxilo Finserve Pvt. Ltd.",
  "Axis Bank Limited-PD":                             "Axis Bank Ltd. - PD",
  "Cent Bank Home Finance Limited":                   "Cent Bank",
  "Chola Investment & Finance - LIP":                 "Chola LIP",
  "DCB Bank Ltd":                                     "DCB Bank",
  "Godrej Capital Limited":                           "Godrej Capital Limited",
  "ICICI Bank Ltd":                                   "ICICI Bank Ltd. - Delhi",
  "ICICI Bank Ltd - Delhi":                           "ICICI Bank Ltd. - Delhi",
  "ICICI Home Finance Co Ltd-PD":                     "",
  "ICICI PD_ilens":                                   "ICICI PD_Ilens",
  "IDFC First Bank Ltd":                              "IDFC First Bank Ltd.",
  "IIFL Home Finance Limited":                        "",
  "India Bulls Housing Finance Ltd - LIP":            "India Bulls Finance / Samman Capital",
  "India Shelter Finance Corp. Ltd-PD":               "India Shelter Finance Corp - PD",
  "Jana Small Finance Bank Ltd-PD":                   "Jana Small Finance Bank",
  "Kotak Mahindra Bank Ltd - PD":                     "Kotak Mahindra Bank Ltd. - PD",
  "Moneyboxx Finance Limited":                        "Moneyboxx Finance Ltd.",
  "Piramal - PD":                                     "Piramal PD",
  "Piramal-UP East PD":                               "Piramal UP East - PD",
  "SMFG India Credit Company Ltd - PD":              "SMFG India Credit Co. - PD",
  "Shivalik Small Finance Bank Ltd.  - PD":           "Shivalik Small Finance Bank - PD",
  "Tata Capital Finance Ltd - Micro Business Loan - PD": "TATA Capital Finance - MBL/BIL",
};

export const DEFAULT_COMPANY_PROFILE: CompanyProfile = {
  name: 'Infominer Verification & Analytics Services',
  tagline: 'Leading Field Verification & Risk Intelligence Solutions',
  addressLine1: 'Corporate Tower B, 4th Floor, Sector 62',
  addressLine2: 'Institutional Area, Tech Zone',
  city: 'Noida',
  state: 'Uttar Pradesh',
  pincode: '201309',
  gstin: '07AAACI1234F1Z8',
  pan: 'AAACI1234F',
  phone: '+91 120 456 7890 / +91 98765 43210',
  email: 'billing@infominer.in',
  website: 'www.infominer.in',
  bankName: 'HDFC Bank Ltd.',
  bankAccountNo: '50200012345678',
  bankIfsc: 'HDFC0001234',
  bankBranch: 'Sector 62, Noida Branch',
  invoicePrefix: 'INF/2026-27/',
  defaultTaxRate: 18,
};

export const DEMO_USERS = [
  { id: 'usr_1', name: 'Eshan Saxena (Admin)', email: 'admin@infominer.in', role: 'admin' as const, avatar: 'ES' },
  { id: 'usr_2', name: 'Rajesh Sharma (Billing Manager)', email: 'billing@infominer.in', role: 'manager' as const, avatar: 'RS' },
  { id: 'usr_3', name: 'Pooja Verma (Compliance Auditor)', email: 'audit@infominer.in', role: 'auditor' as const, avatar: 'PV' },
];

export const SAMPLE_CASES_RAW = [
  {
    client_name: 'Piramal - PD',
    applicant_name: 'Vikram Singh Mehta',
    client_application_number: 'APP-998812',
    city_name: 'Lucknow',
    state: 'Uttar Pradesh',
    product_name: 'Home Loan',
    activity_types: 'Personal Discussion',
    case_status: 'Completed',
    KM_Running_One_Side: 28,
    'KM feeded by MIS': 28,
    tat_received_days: 2,
    verifier_name: 'Amit Kumar',
    case_received_date: '2026-08-01',
    case_closed_date: '2026-08-03',
    Applied_Loan_Amt: 4500000,
    branch_name: 'Hazratganj Branch',
  },
  {
    client_name: 'Piramal - PD',
    applicant_name: 'Sunita Devi & Rajesh',
    client_application_number: 'APP-998813',
    city_name: 'Varanasi',
    state: 'Uttar Pradesh',
    product_name: 'Loan Against Property',
    activity_types: 'Personal Discussion',
    case_status: 'Completed',
    KM_Running_One_Side: 52,
    'KM feeded by MIS': 52,
    tat_received_days: 1,
    verifier_name: 'Rohit Mishra',
    case_received_date: '2026-08-02',
    case_closed_date: '2026-08-03',
    Applied_Loan_Amt: 2800000,
    branch_name: 'Sigra Branch',
  },
  {
    client_name: 'SMFG India Credit Company Ltd - PD',
    applicant_name: 'Gurpreet Singh',
    client_application_number: 'SMFG-55102',
    city_name: 'Gurugram',
    state: 'Haryana',
    product_name: 'Business Loan',
    activity_types: 'PD Verification',
    case_status: 'Completed',
    KM_Running_One_Side: 18,
    'KM feeded by MIS': 18,
    tat_received_days: 3,
    verifier_name: 'Deepak Rao',
    case_received_date: '2026-08-02',
    case_closed_date: '2026-08-05',
    Applied_Loan_Amt: 1500000,
    branch_name: 'Cyber City Branch',
  },
  {
    client_name: 'SMFG India Credit Company Ltd - PD',
    applicant_name: 'Kavita Agarwal',
    client_application_number: 'SMFG-55103',
    city_name: 'Noida',
    state: 'Delhi NCR',
    product_name: 'Micro LAP',
    activity_types: 'PD Verification',
    case_status: 'Completed',
    KM_Running_One_Side: 12,
    'KM feeded by MIS': 12,
    tat_received_days: 1,
    verifier_name: 'Pankaj Saini',
    case_received_date: '2026-08-03',
    case_closed_date: '2026-08-04',
    Applied_Loan_Amt: 950000,
    branch_name: 'Sector 18 Branch',
  },
  {
    client_name: 'Aditya Birla Capital-PD',
    applicant_name: 'Ananya Sharma',
    client_application_number: 'ABC-1092',
    city_name: 'Jaipur',
    state: 'Rajasthan',
    product_name: 'Affordable Housing',
    activity_types: 'Personal Discussion',
    case_status: 'Completed',
    KM_Running_One_Side: 22,
    'KM feeded by MIS': 22,
    tat_received_days: 2,
    verifier_name: 'Vikas Meena',
    case_received_date: '2026-08-04',
    case_closed_date: '2026-08-06',
    Applied_Loan_Amt: 2200000,
    branch_name: 'Tonk Road Branch',
  },
  {
    client_name: 'Aditya Birla Capital-PD',
    applicant_name: 'Manoj Joshi',
    client_application_number: 'ABC-1093',
    city_name: 'Kota',
    state: 'Rajasthan',
    product_name: 'SME Loan',
    activity_types: 'Personal Discussion',
    case_status: 'Completed',
    KM_Running_One_Side: 42,
    'KM feeded by MIS': 42,
    tat_received_days: 3,
    verifier_name: 'Vikas Meena',
    case_received_date: '2026-08-05',
    case_closed_date: '2026-08-08',
    Applied_Loan_Amt: 3500000,
    branch_name: 'Gumanpura Branch',
  },
  {
    client_name: 'IDFC First Bank Ltd',
    applicant_name: 'Rohan Deshmukh',
    client_application_number: 'IDFC-88710',
    city_name: 'Mumbai',
    state: 'Maharashtra',
    product_name: 'Home Loan',
    activity_types: 'Residence & Office PD',
    case_status: 'Completed',
    KM_Running_One_Side: 15,
    'KM feeded by MIS': 15,
    tat_received_days: 1,
    verifier_name: 'Sanjay Shinde',
    case_received_date: '2026-08-05',
    case_closed_date: '2026-08-06',
    Applied_Loan_Amt: 8500000,
    branch_name: 'Andheri East Branch',
  },
  {
    client_name: 'Shivalik Small Finance Bank Ltd.  - PD',
    applicant_name: 'Dinesh Chandra',
    client_application_number: 'SSFB-3301',
    city_name: 'Saharanpur',
    state: 'Uttar Pradesh',
    product_name: 'Micro Business Loan',
    activity_types: 'PD Activity',
    case_status: 'Completed',
    KM_Running_One_Side: 16,
    'KM feeded by MIS': 16,
    tat_received_days: 2,
    verifier_name: 'Rahul Tyagi',
    case_received_date: '2026-08-06',
    case_closed_date: '2026-08-08',
    Applied_Loan_Amt: 700000,
    branch_name: 'Court Road Branch',
  },
  {
    client_name: 'Shivalik Small Finance Bank Ltd.  - PD',
    applicant_name: 'Nitin Mittal',
    client_application_number: 'SSFB-3302',
    city_name: 'Dehradun',
    state: 'Uttarakhand',
    product_name: 'Micro Business Loan',
    activity_types: 'PD Activity',
    case_status: 'Completed',
    KM_Running_One_Side: 35,
    'KM feeded by MIS': 35,
    tat_received_days: 2,
    verifier_name: 'Rahul Tyagi',
    case_received_date: '2026-08-06',
    case_closed_date: '2026-08-08',
    Applied_Loan_Amt: 1200000,
    branch_name: 'Rajpur Road Branch',
  },
  {
    client_name: 'Auxilo Finserve Pvt Ltd',
    applicant_name: 'Shruti Venkat',
    client_application_number: 'AUX-7721',
    city_name: 'Bengaluru',
    state: 'Karnataka',
    product_name: 'Education Loan',
    activity_types: 'Borrower PD',
    case_status: 'Completed',
    KM_Running_One_Side: 14,
    'KM feeded by MIS': 14,
    tat_received_days: 1,
    verifier_name: 'Karthik Nair',
    case_received_date: '2026-08-07',
    case_closed_date: '2026-08-08',
    Applied_Loan_Amt: 4000000,
    branch_name: 'Koramangala Branch',
  },
  {
    client_name: 'Auxilo Finserve Pvt Ltd',
    applicant_name: 'Tanya Banerjee',
    client_application_number: 'AUX-7722',
    city_name: 'Kolkata',
    state: 'West Bengal',
    product_name: 'Education Loan',
    activity_types: 'Borrower PD',
    case_status: 'Completed',
    KM_Running_One_Side: 28,
    'KM feeded by MIS': 28,
    tat_received_days: 2,
    verifier_name: 'Subhash Roy',
    case_received_date: '2026-08-07',
    case_closed_date: '2026-08-09',
    Applied_Loan_Amt: 3200000,
    branch_name: 'Salt Lake Branch',
  },
  {
    client_name: 'Kotak Mahindra Bank Ltd - PD',
    applicant_name: 'Harsh Vardhan',
    client_application_number: 'KMBL-9014',
    city_name: 'New Delhi',
    state: 'Delhi',
    product_name: 'Personal Discussion',
    activity_types: 'PD',
    case_status: 'Completed',
    KM_Running_One_Side: null,
    'KM feeded by MIS': null,
    tat_received_days: 4,
    verifier_name: 'Pankaj Saini',
    case_received_date: '2026-08-08',
    case_closed_date: '2026-08-12',
    Applied_Loan_Amt: 1800000,
    branch_name: 'Connaught Place Branch',
  },
  {
    client_name: 'Jana Small Finance Bank Ltd-PD',
    applicant_name: 'Manish Tiwari',
    client_application_number: 'JSFB-6601',
    city_name: 'Kanpur',
    state: 'Uttar Pradesh',
    product_name: 'Micro Banking',
    activity_types: 'PD',
    case_status: 'PD cancelled not to be billed',
    KM_Running_One_Side: 20,
    'KM feeded by MIS': 20,
    tat_received_days: 1,
    verifier_name: 'Amit Kumar',
    case_received_date: '2026-08-09',
    case_closed_date: '2026-08-10',
    Applied_Loan_Amt: 500000,
    branch_name: 'Mall Road Branch',
  },
];
